### ISSUE TITLE
统计页面报错

### ISSUE THREAD

**Issue by lisanwan** [Redcker/lemonTODO#1]
在点击页面加载的时候报TypeError: Cannot read property 'length' of undefined
![image](https://user-images.githubusercontent.com/73498332/182918324-5442df42-d990-468a-bd2d-cc0ba4172202.png)
![image](https://user-images.githubusercontent.com/73498332/182918479-a79ed34f-c368-4b7c-90d5-1e060fe828db.png)

**Comment by Redcker** [comment]
我没有使用这个方法，可能是模拟器的原因？用真机测试看看

**Comment by Redcker** [comment]
> 在点击页面加载的时候报TypeError: Cannot read property 'length' of undefined ![image](https://user-images.githubusercontent.com/73498332/182918324-5442df42-d990-468a-bd2d-cc0ba4172202.png) ![image](https://user-images.githubusercontent.com/73498332/182918479-a79ed34f-c368-4b7c-90d5-1e060fe828db.png)

我没有使用这个方法，可能是模拟器的原因？用真机测试看看

**Comment by lisanwan** [comment]
嗯嗯。好的，我试试
